/*  
-- Titre        : swissCantons.sql
-- Auteur       : Raphaël Favre

-- Created      : 21.09.2019

-- Version      : 1.0
-- Description  : MySQL Script generating DB "swissCantons" with unique table "cantons" 
    
-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 21:49:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

*/

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema swissCantons
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swissCantons` ;

-- -----------------------------------------------------
-- Schema swissCantons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swissCantons` DEFAULT CHARACTER SET utf8 ;
USE `swissCantons` ;

-- -----------------------------------------------------
-- Table `swissCantons`.`cantons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swissCantons`.`cantons` ;

CREATE TABLE IF NOT EXISTS `swissCantons`.`cantons` (
  `id` SMALLINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(28) NOT NULL,
  `since` SMALLINT NULL,
  `capital` VARCHAR(11) NULL,
  `population` MEDIUMINT NULL,
  `area` DECIMAL(7,2) NULL,
  `nbTowns` SMALLINT NULL,
  `altitudeMax` SMALLINT NULL,
  `altMin` VARCHAR(3) NULL,
  `altMoy` SMALLINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
